version: '3.4'
services:
  user.api:
    image: user.api
    build:
      context: .
      dockerfile: UserMicroservice/User.API/Dockerfile
      args: 
        platform: linux/amd64
    ports:
      - '16153:8080'

  reviews.api:
    image: reviews.api
    build:
      context: .
      dockerfile: ReviewsMicroservice/Reviews.API/Dockerfile
      args:
        platform: linux/amd64
    ports:
      - '16166:8080'

  product.api:
    image: product.api
    build:
      context: .
      dockerfile: ProductMicroservice/Product.API/Dockerfile
      args:
        platform: linux/amd64
    ports:
      - '16168:8080'

  order.api:
    image: order.api
    build:
      context: .
      dockerfile: OrderMicroservice/Order.API/Dockerfile
      args:
        platform: linux/amd64
    ports:
      - '16199:8080'
