name: Trigger auto deployment for order-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'OrderMicroservice/Order.API/**'
    - '.github/workflows/order-container-AutoDeployTrigger-7234ff05-ef10-4924-bc52-4a803543b1c2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ORDERCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}OrderMicroservice/Order.API 
          registryUrl: eshopapplication.azurecr.io
          registryUsername: ${{ secrets.ORDERCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: order-container
          resourceGroup: EShopApplication
          imageToBuild: eshopapplication.azurecr.io/order-container:${{ github.sha }}
          
            

     

