name: Trigger auto deployment for product-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'ProductMicroservice/Product.API/**'
    - '.github/workflows/product-container-AutoDeployTrigger-d03be9d5-7fff-4547-85ba-549cd093080f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRODUCTCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}ProductMicroservice/Product.API 
          registryUrl: eshopapplication.azurecr.io
          registryUsername: ${{ secrets.PRODUCTCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRODUCTCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: product-container
          resourceGroup: EShopApplication
          imageToBuild: eshopapplication.azurecr.io/product-container:${{ github.sha }}
          
            

     

