name: Trigger auto deployment for userapi-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "User.API/**"
      - ".github/workflows/userapi-container-AutoDeployTrigger-5c02f2ea-9e64-469c-9bc7-20d29fa82e1d.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.USERAPICONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: eshopapplication.azurecr.io
          registryUsername: ${{ secrets.USERAPICONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERAPICONTAINER_REGISTRY_PASSWORD }}
          containerAppName: userapi-container
          resourceGroup: rg-eshopapplication-useast
          imageToBuild: eshopapplication.azurecr.io/userapi:${{ github.sha }}
          dockerfilePath: User.API/Dockerfile
