name: Trigger auto deployment for userapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'User.API/**'
    - '.github/workflows/userapi-AutoDeployTrigger-0441d00b-ab48-4701-8aae-654bf39ee173.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.USERAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}User.API 
          registryUrl: eshopapplication.azurecr.io
          registryUsername: ${{ secrets.USERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERAPI_REGISTRY_PASSWORD }}
          containerAppName: userapi
          resourceGroup: AzureDeploymentTest1_group
          imageToBuild: eshopapplication.azurecr.io/userapi:${{ github.sha }}
          
            

     

